services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: authdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d authdb"]
      interval: 5s
      timeout: 3s
      retries: 5


  authentication-service:
    build: .
    container_name: authentication-service
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://admin:admin@db:5432/authdb?schema=public"
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: Admin123!
    ports:
      - "3000:3000"
    command: >
      sh -c "npx prisma migrate deploy && node dist/index.js"


volumes:
  pgdata:
